export enum Stage {
  NEW = 'NEW',
  RUNNING = 'RUNNING',
  FINISHED = 'FINISHED',
}

export enum GameType {
  HERO_REALMS = 'HERO_REALMS',
  HERO_REALMS_CHARACTER_PACKS = 'HERO_REALMS_CHARACTER_PACKS',
}